### ISSUE TITLE
Asymmetric sources are mirrored/rotated badly

### ISSUE THREAD

**Issue by hgeorgsch** [CosmoAI-AES/CosmoSim#132]
Liten bug: Det ser ut som det er en faktor 2 ute og spasserer i \theta. Triangelet har rotert en hel runde når jeg forandrer theta fra 0 til 180 deg

**Comment by hgeorgsch** [comment]
Testing on linux, I get only one round on 360°.  You have to show me, @kosmoben or post screenshots/-cast.

**Comment by bdnormann** [comment]
Compare this one (no rotation) 

![E8AC4A69-6C86-4040-AD1F-27BCD850C377](https://github.com/CosmoAI-AES/CosmoSim/assets/64800540/727d514f-545e-4256-b136-56ead83729dc)

with this one (180 deg rotation)

![53B4AC82-493C-45A6-9406-201FD1A3CAC2](https://github.com/CosmoAI-AES/CosmoSim/assets/64800540/5f199611-fae1-4ee4-b609-32467bbd8b8a)

As far as I can understand the  right-most pictures should be the same except for a rotaiton around the y-axis. But they are not, as one can see from the green bar. So I suspect there is an extra round of rotation or something (spin-2 quantity rather than spin-1 to put it in physics jargon :D )

**Comment by bdnormann** [comment]
(At all rather surprised that one seems to get a 45 degree rotation of the image. compared to the source. Perhaps related to the bug?)

**Comment by hgeorgsch** [comment]
Wrong rotation.

theta is rotation of the source position in polar co-ordinates, and this is correct above.  At 0° the source sits to the right, and at 180° at the left, on the x-axis in either case.

To rotate the source around its centre (or reference point), us source rotation.

Does it look right then?

**Comment by bdnormann** [comment]
Yes, I understand, but it is still wrong in my opinion, as exemplified in the two screen shots above. If you compare the two right-most pictures, the triangle is just shifted to the left in the lower one, compared to the upper one. But that cannot be right, since that does not seem to obey the physical symmetry of the two situations

**Comment by bdnormann** [comment]
(I mean: if you compare the two left-most pictures, there is a mirror symmetry, so there should be one in the two right-most ones too, since the lens is symmetric)

**Comment by hgeorgsch** [comment]
Yes.  You are right.  It has nothing to do with theta though, which has the right effect on the left hand images.

**Comment by hgeorgsch** [comment]
Main problem was Mat.at( cv::Point2d ) swapping x- and y-coordinates.  This has now been fixed on bug/rotation, with some further fixes to Raytrace to make it look right.  This causes regression errors, but for the spherical sources, they are relatively minor, and can be put down to numerical errors.
